name: GitHub to CodeCommit Sync
run-name: Syncing to CodeCommit...
 
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  delete:
 
permissions:
    id-token: write
    contents: read
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
           
      - name: Mirror to CodeCommit
        run: |
          git config --global credential."${{ vars.CODECOMMIT_URL }}".helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true
          git remote add mirror "${{ vars.CODECOMMIT_URL }}"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"